version: 1.4.8
skip_branch_with_pr: true
image: Visual Studio 2017
clone_folder: c:\projects\AutoUpdater.NET
platform:
  - Any CPU
configuration:
  - Release
  - Release-NET35
  - Release-NET40
  - Release-NET452
  - Release-NET462
environment:
  my_secret:
    secure: vbPRaZLQYpGPr4BrZZ4p6TofpSZMud+FKtlpqjgO8aA=
install:
- nuget install secure-file -ExcludeVersion
- secure-file\tools\secure-file -decrypt "c:\projects\AutoUpdater.NET\ZipExtractor\ZipExtractor.snk.enc" -secret %my_secret%
- secure-file\tools\secure-file -decrypt "c:\projects\AutoUpdater.NET\AutoUpdater.NET\AutoUpdater.NET.snk.enc" -secret %my_secret%
before_build:
- cmd: nuget restore
build:
  verbosity: minimal
after_build:
- nuget pack "c:\projects\AutoUpdater.NET\AutoUpdater.NET\build\Autoupdater.NET.Official.nuspec"
- cmd: 7z a AutoUpdater.NET-%APPVEYOR_BUILD_VERSION%.zip %APPVEYOR_BUILD_FOLDER%\build\lib\
artifacts:
- path: AutoUpdater.NET-$(APPVEYOR_BUILD_VERSION).zip
- path: AutoUpdater.NET\build\Autoupdater.NET.Official.$(APPVEYOR_BUILD_VERSION).nupkg

deploy:
- provider: GitHub
  release: $(APPVEYOR_REPO_TAG_NAME)
  description: '// TODO: Write Release Notes'
  auth_token:
    secure: WHW27Nvc8zNhfyhxIYdl/NwbrkFzvSX0vE4/CS8iByPXM6rcztWhUrDXJ7eejLBY
  draft: false
  prerelease: false
  on:
    branch: master                 # release from master branch only
    appveyor_repo_tag: true        # deploy on tag push only

- provider: NuGet
  api_key:
    secure: f061iyHEh8+Fz3+iV/c+3stBhQuyndcJMP719Eny9w6sbRfMgD1yJe+aVAYW1PJD
  skip_symbols: false
  artifact: /.*\.nupkg/
  on:
    branch: master                 # release from master branch only
    appveyor_repo_tag: true        # deploy on tag push only